import type { Metadata } from "next";
import { Geist, Geist_Mono , Mulish} from "next/font/google";
import "./globals.css";
import ReduxProvider from "./provider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const mulish = Mulish({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'], 
  variable: '--font-mulish',
});


export const metadata: Metadata = {
  title: "Forge",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable}  ${geistMono.variable} ${mulish.variable} antialiased`}
      >
         {/* Include Optima Nova from CDN */}
        <link
          href="https://fonts.cdnfonts.com/css/optima-nova-lt-pro"
          rel="stylesheet"
        />

        <ReduxProvider>

        {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
